package maryk.foundationdb

expect class NetworkOptions {
    fun setTraceEnable(path: String?)
    fun setTraceRollSize(bytes: Long)
    fun setTraceMaxLogsSize(bytes: Long)
    fun setTraceLogGroup(logGroup: String)
    fun setTraceFormat(format: String)
    fun setTraceClockSource(clock: String)
    fun setTraceFileIdentifier(identifier: String)
    fun setTraceShareAmongClientThreads()
    fun setTraceInitializeOnSetup()
    fun setTracePartialFileSuffix(suffix: String)
    fun setKnob(knob: String)
    fun setTLSCertBytes(bytes: ByteArray)
    fun setTLSCertPath(path: String)
    fun setTLSKeyBytes(bytes: ByteArray)
    fun setTLSKeyPath(path: String)
    fun setTLSVerifyPeers(pattern: ByteArray)
    fun setBuggifyEnable()
    fun setBuggifyDisable()
    fun setClientBuggifyEnable()
    fun setClientBuggifyDisable()
    fun setClientBuggifySectionActivatedProbability(percentage: Long)
    fun setClientBuggifySectionFiredProbability(percentage: Long)
    fun setDistributedClientTracer(value: String)
    fun setClientTmpDir(path: String)
    fun setEnableRunLoopProfiling()
    fun setDisableClientBypass()
}
