package maryk.foundationdb

/**
 * Tunable settings applied to a single transaction.
 *
 * The surface below mirrors the most commonly used FoundationDB transaction options.
 */
interface TransactionOptionSink {
    fun setCausalWriteRisky()
    fun setCausalReadRisky()
    fun setIncludePortInAddress()
    fun setCausalReadDisable()
    fun setReadYourWritesDisable()
    fun setNextWriteNoWriteConflictRange()
    fun setSnapshotRywEnable()
    fun setSnapshotRywDisable()
    fun setReadServerSideCacheEnable()
    fun setReadServerSideCacheDisable()
    fun setReadPriorityNormal()
    fun setReadPriorityLow()
    fun setReadPriorityHigh()
    fun setPrioritySystemImmediate()
    fun setPriorityBatch()
    fun setInitializeNewDatabase()
    fun setAccessSystemKeys()
    fun setReadSystemKeys()
    fun setRawAccess()
    fun setBypassStorageQuota()
    fun setDebugTransactionIdentifier(value: String)
    fun setLogTransaction()
    fun setTransactionLoggingMaxFieldLength(value: Long)
    fun setServerRequestTracing()
    fun setTimeout(value: Long)
    fun setRetryLimit(value: Long)
    fun setMaxRetryDelay(value: Long)
    fun setSizeLimit(value: Long)
    fun setAutomaticIdempotency()
    fun setLockAware()
    fun setReadLockAware()
    fun setUsedDuringCommitProtectionDisable()
    fun setUseProvisionalProxies()
    fun setReportConflictingKeys()
    fun setSpecialKeySpaceRelaxed()
    fun setSpecialKeySpaceEnableWrites()
    fun setTag(value: String)
    fun setAutoThrottleTag(value: String)
    fun setSpanParent(value: ByteArray)
    fun setExpensiveClearCostEstimationEnable()
    fun setBypassUnreadable()
    fun setUseGrvCache()
    fun setAuthorizationToken(value: String)
    fun setDurabilityDatacenter()
    fun setDurabilityRisky()
    fun setDebugRetryLogging(value: String)
}

expect class TransactionOptions : TransactionOptionSink {
    override fun setCausalWriteRisky()
    override fun setCausalReadRisky()
    override fun setIncludePortInAddress()
    override fun setCausalReadDisable()
    override fun setReadYourWritesDisable()
    override fun setNextWriteNoWriteConflictRange()
    override fun setSnapshotRywEnable()
    override fun setSnapshotRywDisable()
    override fun setReadServerSideCacheEnable()
    override fun setReadServerSideCacheDisable()
    override fun setReadPriorityNormal()
    override fun setReadPriorityLow()
    override fun setReadPriorityHigh()
    override fun setPrioritySystemImmediate()
    override fun setPriorityBatch()
    override fun setInitializeNewDatabase()
    override fun setAccessSystemKeys()
    override fun setReadSystemKeys()
    override fun setRawAccess()
    override fun setBypassStorageQuota()
    override fun setDebugTransactionIdentifier(value: String)
    override fun setLogTransaction()
    override fun setTransactionLoggingMaxFieldLength(value: Long)
    override fun setServerRequestTracing()
    override fun setTimeout(value: Long)
    override fun setRetryLimit(value: Long)
    override fun setMaxRetryDelay(value: Long)
    override fun setSizeLimit(value: Long)
    override fun setAutomaticIdempotency()
    override fun setLockAware()
    override fun setReadLockAware()
    override fun setUsedDuringCommitProtectionDisable()
    override fun setUseProvisionalProxies()
    override fun setReportConflictingKeys()
    override fun setSpecialKeySpaceRelaxed()
    override fun setSpecialKeySpaceEnableWrites()
    override fun setTag(value: String)
    override fun setAutoThrottleTag(value: String)
    override fun setSpanParent(value: ByteArray)
    override fun setExpensiveClearCostEstimationEnable()
    override fun setBypassUnreadable()
    override fun setUseGrvCache()
    override fun setAuthorizationToken(value: String)
    override fun setDurabilityDatacenter()
    override fun setDurabilityRisky()
    override fun setDebugRetryLogging(value: String)
}
