package maryk.foundationdb

/**
 * Tunable settings applied to a single transaction.
 *
 * The surface below mirrors the most commonly used FoundationDB transaction options.
 */
expect class TransactionOptions {
    fun setCausalWriteRisky()
    fun setCausalReadRisky()
    fun setIncludePortInAddress()
    fun setCausalReadDisable()
    fun setReadYourWritesDisable()
    fun setNextWriteNoWriteConflictRange()
    fun setReadAheadDisable()
    fun setSnapshotRywEnable()
    fun setSnapshotRywDisable()
    fun setReadServerSideCacheEnable()
    fun setReadServerSideCacheDisable()
    fun setReadPriorityNormal()
    fun setReadPriorityLow()
    fun setReadPriorityHigh()
    fun setDurabilityDevNullIsWebScale()
    fun setPrioritySystemImmediate()
    fun setPriorityBatch()
    fun setInitializeNewDatabase()
    fun setAccessSystemKeys()
    fun setReadSystemKeys()
    fun setRawAccess()
    fun setBypassStorageQuota()
    fun setTransactionLoggingEnable(value: String)
    fun setDebugTransactionIdentifier(value: String)
    fun setLogTransaction()
    fun setTransactionLoggingMaxFieldLength(value: Long)
    fun setServerRequestTracing()
    fun setTimeout(value: Long)
    fun setRetryLimit(value: Long)
    fun setMaxRetryDelay(value: Long)
    fun setSizeLimit(value: Long)
    fun setAutomaticIdempotency()
    fun setLockAware()
    fun setReadLockAware()
    fun setUsedDuringCommitProtectionDisable()
    fun setUseProvisionalProxies()
    fun setReportConflictingKeys()
    fun setSpecialKeySpaceRelaxed()
    fun setSpecialKeySpaceEnableWrites()
    fun setTag(value: String)
    fun setAutoThrottleTag(value: String)
    fun setSpanParent(value: ByteArray)
    fun setExpensiveClearCostEstimationEnable()
    fun setBypassUnreadable()
    fun setUseGrvCache()
    fun setAuthorizationToken(value: String)
    fun setDurabilityDatacenter()
    fun setDurabilityRisky()
    fun setDebugRetryLogging(value: String)
}
