package maryk.foundationdb

actual class TransactionOptions internal constructor(
    internal val delegate: com.apple.foundationdb.TransactionOptions
) : TransactionOptionSink {
    actual override fun setCausalWriteRisky() = delegate.setCausalWriteRisky()
    actual override fun setCausalReadRisky() = delegate.setCausalReadRisky()
    actual override fun setIncludePortInAddress() = delegate.setIncludePortInAddress()
    actual override fun setCausalReadDisable() = delegate.setCausalReadDisable()
    actual override fun setReadYourWritesDisable() = delegate.setReadYourWritesDisable()
    actual override fun setNextWriteNoWriteConflictRange() = delegate.setNextWriteNoWriteConflictRange()
    actual override fun setSnapshotRywEnable() = delegate.setSnapshotRywEnable()
    actual override fun setSnapshotRywDisable() = delegate.setSnapshotRywDisable()
    actual override fun setReadServerSideCacheEnable() = delegate.setReadServerSideCacheEnable()
    actual override fun setReadServerSideCacheDisable() = delegate.setReadServerSideCacheDisable()
    actual override fun setReadPriorityNormal() = delegate.setReadPriorityNormal()
    actual override fun setReadPriorityLow() = delegate.setReadPriorityLow()
    actual override fun setReadPriorityHigh() = delegate.setReadPriorityHigh()
    actual override fun setPrioritySystemImmediate() = delegate.setPrioritySystemImmediate()
    actual override fun setPriorityBatch() = delegate.setPriorityBatch()
    actual override fun setInitializeNewDatabase() = delegate.setInitializeNewDatabase()
    actual override fun setAccessSystemKeys() = delegate.setAccessSystemKeys()
    actual override fun setReadSystemKeys() = delegate.setReadSystemKeys()
    actual override fun setRawAccess() = delegate.setRawAccess()
    actual override fun setBypassStorageQuota() = delegate.setBypassStorageQuota()
    actual override fun setDebugTransactionIdentifier(value: String) = delegate.setDebugTransactionIdentifier(value)
    actual override fun setLogTransaction() = delegate.setLogTransaction()
    actual override fun setTransactionLoggingMaxFieldLength(value: Long) = delegate.setTransactionLoggingMaxFieldLength(value)
    actual override fun setServerRequestTracing() = delegate.setServerRequestTracing()
    actual override fun setTimeout(value: Long) = delegate.setTimeout(value)
    actual override fun setRetryLimit(value: Long) = delegate.setRetryLimit(value)
    actual override fun setMaxRetryDelay(value: Long) = delegate.setMaxRetryDelay(value)
    actual override fun setSizeLimit(value: Long) = delegate.setSizeLimit(value)
    actual override fun setAutomaticIdempotency() = delegate.setAutomaticIdempotency()
    actual override fun setLockAware() = delegate.setLockAware()
    actual override fun setReadLockAware() = delegate.setReadLockAware()
    actual override fun setUsedDuringCommitProtectionDisable() = delegate.setUsedDuringCommitProtectionDisable()
    actual override fun setUseProvisionalProxies() = delegate.setUseProvisionalProxies()
    actual override fun setReportConflictingKeys() = delegate.setReportConflictingKeys()
    actual override fun setSpecialKeySpaceRelaxed() = delegate.setSpecialKeySpaceRelaxed()
    actual override fun setSpecialKeySpaceEnableWrites() = delegate.setSpecialKeySpaceEnableWrites()
    actual override fun setTag(value: String) = delegate.setTag(value)
    actual override fun setAutoThrottleTag(value: String) = delegate.setAutoThrottleTag(value)
    actual override fun setSpanParent(value: ByteArray) = delegate.setSpanParent(value)
    actual override fun setExpensiveClearCostEstimationEnable() = delegate.setExpensiveClearCostEstimationEnable()
    actual override fun setBypassUnreadable() = delegate.setBypassUnreadable()
    actual override fun setUseGrvCache() = delegate.setUseGrvCache()
    actual override fun setAuthorizationToken(value: String) = delegate.setAuthorizationToken(value)
    actual override fun setDurabilityDatacenter() = delegate.setDurabilityDatacenter()
    actual override fun setDurabilityRisky() = delegate.setDurabilityRisky()
    actual override fun setDebugRetryLogging(value: String) = delegate.setDebugRetryLogging(value)
}
