package maryk.foundationdb

actual class TransactionOptions internal constructor(
    internal val delegate: com.apple.foundationdb.TransactionOptions
) {
    actual fun setCausalWriteRisky() = delegate.setCausalWriteRisky()
    actual fun setCausalReadRisky() = delegate.setCausalReadRisky()
    actual fun setIncludePortInAddress() = delegate.setIncludePortInAddress()
    actual fun setCausalReadDisable() = delegate.setCausalReadDisable()
    actual fun setReadYourWritesDisable() = delegate.setReadYourWritesDisable()
    actual fun setNextWriteNoWriteConflictRange() = delegate.setNextWriteNoWriteConflictRange()
    actual fun setReadAheadDisable() = delegate.setReadAheadDisable()
    actual fun setSnapshotRywEnable() = delegate.setSnapshotRywEnable()
    actual fun setSnapshotRywDisable() = delegate.setSnapshotRywDisable()
    actual fun setReadServerSideCacheEnable() = delegate.setReadServerSideCacheEnable()
    actual fun setReadServerSideCacheDisable() = delegate.setReadServerSideCacheDisable()
    actual fun setReadPriorityNormal() = delegate.setReadPriorityNormal()
    actual fun setReadPriorityLow() = delegate.setReadPriorityLow()
    actual fun setReadPriorityHigh() = delegate.setReadPriorityHigh()
    actual fun setDurabilityDevNullIsWebScale() = delegate.setDurabilityDevNullIsWebScale()
    actual fun setPrioritySystemImmediate() = delegate.setPrioritySystemImmediate()
    actual fun setPriorityBatch() = delegate.setPriorityBatch()
    actual fun setInitializeNewDatabase() = delegate.setInitializeNewDatabase()
    actual fun setAccessSystemKeys() = delegate.setAccessSystemKeys()
    actual fun setReadSystemKeys() = delegate.setReadSystemKeys()
    actual fun setRawAccess() = delegate.setRawAccess()
    actual fun setBypassStorageQuota() = delegate.setBypassStorageQuota()
    actual fun setTransactionLoggingEnable(value: String) = delegate.setTransactionLoggingEnable(value)
    actual fun setDebugTransactionIdentifier(value: String) = delegate.setDebugTransactionIdentifier(value)
    actual fun setLogTransaction() = delegate.setLogTransaction()
    actual fun setTransactionLoggingMaxFieldLength(value: Long) = delegate.setTransactionLoggingMaxFieldLength(value)
    actual fun setServerRequestTracing() = delegate.setServerRequestTracing()
    actual fun setTimeout(value: Long) = delegate.setTimeout(value)
    actual fun setRetryLimit(value: Long) = delegate.setRetryLimit(value)
    actual fun setMaxRetryDelay(value: Long) = delegate.setMaxRetryDelay(value)
    actual fun setSizeLimit(value: Long) = delegate.setSizeLimit(value)
    actual fun setAutomaticIdempotency() = delegate.setAutomaticIdempotency()
    actual fun setLockAware() = delegate.setLockAware()
    actual fun setReadLockAware() = delegate.setReadLockAware()
    actual fun setUsedDuringCommitProtectionDisable() = delegate.setUsedDuringCommitProtectionDisable()
    actual fun setUseProvisionalProxies() = delegate.setUseProvisionalProxies()
    actual fun setReportConflictingKeys() = delegate.setReportConflictingKeys()
    actual fun setSpecialKeySpaceRelaxed() = delegate.setSpecialKeySpaceRelaxed()
    actual fun setSpecialKeySpaceEnableWrites() = delegate.setSpecialKeySpaceEnableWrites()
    actual fun setTag(value: String) = delegate.setTag(value)
    actual fun setAutoThrottleTag(value: String) = delegate.setAutoThrottleTag(value)
    actual fun setSpanParent(value: ByteArray) = delegate.setSpanParent(value)
    actual fun setExpensiveClearCostEstimationEnable() = delegate.setExpensiveClearCostEstimationEnable()
    actual fun setBypassUnreadable() = delegate.setBypassUnreadable()
    actual fun setUseGrvCache() = delegate.setUseGrvCache()
    actual fun setAuthorizationToken(value: String) = delegate.setAuthorizationToken(value)
    actual fun setDurabilityDatacenter() = delegate.setDurabilityDatacenter()
    actual fun setDurabilityRisky() = delegate.setDurabilityRisky()
    actual fun setDebugRetryLogging(value: String) = delegate.setDebugRetryLogging(value)
}
